### ISSUE TITLE
Can’t add printer due to no “dot” in numpad

### ISSUE THREAD

**Issue by kawlsson** [dunkmann00/PrusaLinkiOS#2]
When I try to add a printer I can’t add the printer. 
When I try to input the IP-address there only comma available. See attached picture. 
running on iOS 17.0.3 iPhone 13 mini. 
let me know if there’s any more information needed. 

I’m very curious on this app, looks promising!
I appreciate your efforts :)

![IMG_6815](https://github.com/dunkmann00/PrusaLinkiOS/assets/67454783/b869d942-314b-418b-b634-3b72f31808be)

**Comment by dunkmann00** [comment]
I didn't realize in some locales a comma is used rather than a period for the decimal point! I'll have to figure out a way to get around this!

As a workaround for now, you could type the IP address in something else, like the notes app for example, and copy and paste it in with `.`'s instead of `,`'s.

Thanks for checking out the app and bringing this issue to my attention!

**Comment by kawlsson** [comment]
Ah, of course. 
I was tired when I tried it last night :)
I feel like an idiot. 
I will verify when I get a chance. 

Thank you

**Comment by elvito** [comment]
Same problem here. No dot available only comma. I use german language settings. I will try to c&p the IP address.

**Comment by jurrien-suse** [comment]
Could you also add dns support?
